apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-pubsub
spec:
  type: pubsub.aws.snssqs
  version: v1
  metadata:
  - name: region
    value: us-east-2
  - name: snsTopic
    value: "orders-topic"
  - name: sqsQueueName
    value: "orders-queue"
  # - name: awsAccessKey
  #   value: "<AWS_ACCESS_KEY>"
  # - name: awsSecretKey
  #   value: "<AWS_SECRET_KEY>"


