apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: orderservice-sub
  namespace: default
spec:
  topic: orders                 # must match the topic your publisher is sending
  route: /orders                # endpoint in your orderservice to receive events
  pubsubname: order-pubsub        # must match your Dapr pubsub component
  version: v1
